language: java
install: true
sudo: required

services:
  - docker

before_install:
  - docker network create heimdall_network
  - docker run --name heimdall-demo-mongo --network=heimdall_network -d mongo
  - docker ps -a

jdk:
  - oraclejdk8
os:
  - linux
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.gradle

after_success:
  - bash <(curl -s https://codecov.io/bash)