spring:
  application:
    name: heimdall
  profiles:
    active: local
server:
  port: 9001
logging:
  level:
    root: erro
    org.springframework.data: debug
    
---

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://heimdall-demo-mongo/heimdall
      
---

spring:
  profiles: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: heimdall