spring:
  application:
    name: heimdall
  data:
    mongodb:
      uri: mongodb://heimdall-demo-mongo/heimdall 
server:
  port: 9001
logging:
  level:
    root: error
    org.springframework.data: debug